loggers:
  EXECENGINE:
    handlers: [stdout, stderr]
  IO:
    handlers: [stdout, stderr]
  API:
    handlers: [stdout, stderr]
  APPLICATION:
    handlers: [stdout, stderr]
  DATABASE:
    handlers: [stdout, stderr]
  CORE:
    handlers: [stdout, stderr]
  RULEENGINE:
    handlers: [stdout, stderr]
  TRANSACTION:
    handlers: [stdout, stderr]
  INTERFACING:
    handlers: [stdout, stderr]
formatters:
handlers:
  stderr:
    class: Monolog\Handler\StreamHandler
    level: WARNING
    processors: [request_id_processor, web_processor]
    stream: php://stderr
  stdout-stream:
    class: Monolog\Handler\StreamHandler
    level: DEBUG
    processors: [request_id_processor, web_processor]
    stream: php://stdout
  stdout:
    class: Monolog\Handler\FingersCrossedHandler
    handler: stdout-stream
    passthruLevel: NOTICE
    activationStrategy: ERROR
processors:
  web_processor:
    class: Monolog\Processor\WebProcessor
    serverData: null
    extraFields:
      ip: REMOTE_ADDR
      method: REQUEST_METHOD
      url: REQUEST_URI
  request_id_processor:
    class: Ampersand\Log\RequestIDProcessor